spring.application.name=api-gateway

server.port=8765

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka